site_name: Setyawan Bekti Wibowo
site_url: https://setyawanbw.github.io/
site_description: Note and Documentation by SBW
site_author: Setyawan Bekti Wibowo

repo_url: https://setyawanbw.github.io/

copyright: Copyright &copy; 2014 <a href="https://twitter.com/_setyawanbw">Setyawan</a>

theme:
    name: flatly

markdown_extensions:
    - toc:
        permalink: '#'

plugins:
    - search
